"""Hand-written phrasing bank for ReAct v3 tool-SFT data (reviewed by hand, no API generation).

The generator splits every category into train/val/test template families by a stable hash,
so val/test phrasings never appear in training. Placeholders:
  {speed_q} {hours_q} {distance_q} {value_q}  quantities with a unit word
  {au} {to_u}                                 a unit word for the answer / conversion target
  {card}                                      a voyage-card reference containing its id
  {q}                                         an OceanInstruct question
  {e}                                         a record already given to the model
Templates contain no digits and no '<' '>' so numbers only come from placeholders.
"""

UNIT_SURFACES = {
    "km": ["km", "公里", "千米"], "m": ["m", "米"], "nmi": ["nmi", "海里"],
    "km/h": ["km/h", "公里/小时", "公里每小时", "千米/小时", "千米每小时"],
    "kn": ["kn", "节"], "m/s": ["m/s", "米/秒", "米每秒"], "h": ["h", "小时", "个小时"],
}
# Card references inside English templates (vocabulary only, not a phrasing family).
ENGLISH_CARD_REFS = ["card {cid}", "voyage card {cid}", "record {cid}"]
ENGLISH_UNIT_SURFACES = {
    "km": ["km"], "m": ["m"], "nmi": ["nmi", "nautical miles"], "km/h": ["km/h"],
    "kn": ["kn", "knots"], "m/s": ["m/s"], "h": ["h", "hours"],
}

CATEGORIES = {
    # Generic openers; drawn independently of the task kind so they cannot act as a trigger.
    "prefix": [
        "请帮忙：", "问题：", "请帮我看看：", "【航次记录】", "调查船日志：", "Q：", "请协助处理：", "值班记录：",
        "海上问答：", "工作单：", "需求：", "咨询：", "提问：", "请处理这条请求：", "航海日志摘录：", "【请求】",
        "用户：", "现场记录：", "科考队提问：", "作业指令：", "Hi，", "你好，", "麻烦你，", "请回答：",
        "练习题：", "【海洋助手】", "船上同事问：", "实验室来电：", "Task: ", "Question: ", "请看：", "急：",
        "备注：本题来自练习材料。", "【练习】", "下面是一个问题。", "请注意：", "工单编号省略。", "（模拟场景）",
        "调度中心：", "站位记录员提问：",
    ],
    # Output instructions for numeric tasks (the generator also leaves some questions without one).
    "suffix": [
        "直接给出数值和单位。", "答案写成“数值 单位”。", "不用解释过程。", "请给出结果。",
        "结果带上单位。", "简短回答即可。", "只要最终结果。", "回答尽量简洁。", "给我一个带单位的数。",
        "Answer with number and unit.", "请直接回复结果。", "不需要推导过程。", "一句话回答。",
        "最后只写数值和单位。", "用工具算准一些。", "按工具结果回答。", "无需多余说明。", "请写出数值及其单位。",
    ],
    "card_ref": [
        "航次卡{cid}", "{cid}号航次卡", "编号{cid}的航次记录", "航次记录{cid}", "卡片{cid}",
        "{cid}这张航次卡", "航次{cid}", "记录卡 {cid}", "{cid}号记录", "模拟卡{cid}", "资料编号{cid}",
    ],
    "calc.distance": [
        "船速{speed_q}，航行{hours_q}，航程是多少？",
        "调查船以{speed_q}的速度连续航行了{hours_q}，一共走了多远？",
        "按{speed_q}匀速行驶{hours_q}，请计算航行距离。",
        "航速取{speed_q}，航行时间取{hours_q}，对应航程是多少？",
        "一艘科考船开了{hours_q}，速度一直是{speed_q}，它跑了多少{au}？",
        "{hours_q}内保持{speed_q}，这段时间的里程是多少？",
        "请算一下：速度{speed_q}、时间{hours_q}时的航行距离。",
        "如果船以{speed_q}航行{hours_q}，能走多少{au}？",
        "航速记录为{speed_q}，持续航行{hours_q}，这段航程有多长？",
        "speed {speed_q}, duration {hours_q}. How far did the vessel travel?",
        "Calculate the distance covered at {speed_q} over {hours_q}.",
        "我们的船{speed_q}走了{hours_q}，总共航行了多少{au}？",
        "考察船巡航速度{speed_q}，巡航{hours_q}后的总里程是多少？",
        "以{speed_q}的航速出发并直线航行{hours_q}，此时离出发点多远？",
        "航行{hours_q}，平均航速{speed_q}，航行距离是多少？",
        "计算航段长度：航速{speed_q}，用时{hours_q}。",
        "测量船匀速{speed_q}，作业航行{hours_q}，问航程？",
        "船舶在{hours_q}里以{speed_q}前进，走过的路程是多少{au}？",
        "麻烦帮我算下距离，速度是{speed_q}，开了{hours_q}。",
        "给定航速{speed_q}和航时{hours_q}，输出航程。",
        "从港口出发后以{speed_q}航行了{hours_q}，这一段航程多长？",
        "拖网作业船以{speed_q}拖曳{hours_q}，拖曳距离是多少？",
        "浮标布放船航速{speed_q}，到达前共航行{hours_q}，航程为多少{au}？",
        "时间{hours_q}，速度{speed_q}，距离等于多少？",
        "这艘船的速度是{speed_q}，它航行{hours_q}能覆盖多少{au}的航线？",
        "保持{speed_q}不变，再航行{hours_q}还能前进多少{au}？",
        "请求计算：v={speed_q}，t={hours_q}，求s。",
        "调查船昨夜以{speed_q}连续航行{hours_q}，请算出夜间航程。",
        "按照{speed_q}的航速，{hours_q}的航行能走多远？",
        "What is the distance in {au} for a ship moving at {speed_q} for {hours_q}?",
        "补给船{hours_q}内以{speed_q}航行，这段航行有多少{au}？",
        "航速{speed_q}的船只航行了{hours_q}，请给出航行距离。",
        "求距离：船速{speed_q}，时长{hours_q}。",
        "一次走航观测中，船速{speed_q}，观测持续{hours_q}，走航距离是多少？",
        "如果航速是{speed_q}、航行时间是{hours_q}，那么航程应该是多少？",
        "科考船以{speed_q}驶向站位，航行{hours_q}后抵达，站位离出发点有多远？",
        "请估算航程：以{speed_q}行驶{hours_q}。",
        "船以{speed_q}航行，共用了{hours_q}，总航程是多少？",
        "在{hours_q}的航行里，船速稳定在{speed_q}，求总航程。",
        "Distance? Speed {speed_q}, time {hours_q}.",
    ],
    "calc.speed": [
        "{hours_q}航行了{distance_q}，平均航速是多少？",
        "调查船用{hours_q}走完{distance_q}，速度是多少{au}？",
        "航程{distance_q}，用时{hours_q}，求平均速度。",
        "这艘船{hours_q}跑了{distance_q}，它开得有多快？",
        "请计算航速：距离{distance_q}，时间{hours_q}。",
        "科考船完成{distance_q}的测线用了{hours_q}，平均船速是多少？",
        "如果{hours_q}内要航行{distance_q}，需要保持多大的航速？",
        "航行距离为{distance_q}，航行时间为{hours_q}，平均速度为多少{au}？",
        "Average speed for {distance_q} in {hours_q}?",
        "The ship covered {distance_q} in {hours_q}. What was its average speed?",
        "我们{hours_q}开了{distance_q}，平均一小时走多少公里？",
        "从甲站到乙站共{distance_q}，航行耗时{hours_q}，平均航速多少？",
        "求速度：s={distance_q}，t={hours_q}。",
        "拖网船{hours_q}拖了{distance_q}，拖曳速度是多少？",
        "走航观测覆盖{distance_q}，持续{hours_q}，请算平均航速。",
        "船只在{hours_q}里前进了{distance_q}，速度为多少{au}？",
        "给定航程{distance_q}和航时{hours_q}，输出平均航速。",
        "补给船用{hours_q}抵达{distance_q}外的平台，平均速度是多少？",
        "这段{distance_q}的航线，船开了{hours_q}，平均开多快？",
        "想知道平均航速：航程一共{distance_q}，用时一共{hours_q}。",
        "测量船{hours_q}完成了{distance_q}的扫测，扫测航速是多少{au}？",
        "Compute the mean speed: distance {distance_q}, time {hours_q}.",
        "请根据航程{distance_q}和航行时长{hours_q}算出速度。",
        "一共航行{distance_q}，花了{hours_q}，平均每小时走多少？",
        "科考船出港{hours_q}后已离港{distance_q}，它的平均航速是？",
        "要在{hours_q}内完成{distance_q}航段，平均速度应为多少{au}？",
        "航次中某航段长{distance_q}，航行了{hours_q}，求该航段航速。",
        "船速多少？距离{distance_q}，时间{hours_q}。",
        "浮标回收船用{hours_q}开过{distance_q}，算一下它的速度。",
        "日志里只写了：航程{distance_q}，历时{hours_q}。请推算航速。",
        "考察船在{hours_q}内航行{distance_q}，求航速。",
        "麻烦算一下速度：开了{distance_q}，用了{hours_q}。",
        "船以恒定速度在{hours_q}内驶过{distance_q}，这个速度是多少？",
        "What speed is needed to travel {distance_q} in {hours_q}?",
        "{distance_q}的距离用{hours_q}走完，平均速度多少{au}？",
        "请计算平均速度，已知该船{hours_q}航行{distance_q}。",
        "船舶航行{distance_q}耗时{hours_q}，求其平均航速。",
        "科考船连续作业{hours_q}，期间航行{distance_q}，平均航速为多少？",
        "这条航线长{distance_q}，船开了{hours_q}，平均速度是多少？",
        "按{hours_q}走完{distance_q}来算，船的平均航速是多少{au}？",
    ],
    "calc.time": [
        "航程{distance_q}，船速{speed_q}，需要多长时间？",
        "以{speed_q}航行{distance_q}要多久？",
        "距离{distance_q}，速度{speed_q}，求航行时间。",
        "调查船要去{distance_q}外的站位，航速{speed_q}，几个小时能到？",
        "按{speed_q}的速度，走完{distance_q}需要多少{au}？",
        "请计算航行时长：航程{distance_q}，航速{speed_q}。",
        "科考船以{speed_q}行驶，完成{distance_q}的测线需要多久？",
        "How long does it take to cover {distance_q} at {speed_q}?",
        "Travel time for {distance_q} at {speed_q}?",
        "{distance_q}的航线，保持{speed_q}，要开几个小时？",
        "补给船距平台{distance_q}，航速{speed_q}，预计多长时间抵达？",
        "如果船速是{speed_q}，航行{distance_q}要花多少{au}？",
        "求时间：s={distance_q}，v={speed_q}。",
        "从港口到观测点{distance_q}，船以{speed_q}前进，需要航行多久？",
        "这艘船{speed_q}，要跑{distance_q}，得多长时间？",
        "给定航程{distance_q}与航速{speed_q}，输出所需时长。",
        "拖网船以{speed_q}拖曳{distance_q}，拖曳时间是多少？",
        "测量船要完成{distance_q}扫测，扫测速度{speed_q}，需要多少{au}？",
        "驶过{distance_q}需要多少时间？航速是{speed_q}。",
        "我们离目的地还有{distance_q}，现在速度{speed_q}，还要开多久？",
        "航行{distance_q}，速度保持{speed_q}，用时为多少{au}？",
        "Compute the time needed: distance {distance_q}, speed {speed_q}.",
        "到下一个站位{distance_q}，若船速{speed_q}，需要几小时？",
        "请推算航时：航段长{distance_q}，航速{speed_q}。",
        "船速恒定为{speed_q}，走完{distance_q}一共要多少时间？",
        "去{distance_q}外的海域，开{speed_q}的话路上要多久？",
        "完成{distance_q}航程所需时间是多少？航速为{speed_q}。",
        "考察船计划以{speed_q}航行{distance_q}，计划航时是多少{au}？",
        "Time required to sail {distance_q} at {speed_q}, in {au}?",
        "走航{distance_q}，航速{speed_q}，走航时长多少？",
        "按{speed_q}计算，{distance_q}的路程要航行多久？",
        "以{speed_q}的速度穿越{distance_q}宽的海峡要多长时间？",
        "航速{speed_q}的船驶过{distance_q}需要几个小时？",
        "船速{speed_q}，航程{distance_q}，航行时间等于多少？",
        "浮标布放点在{distance_q}以外，船开{speed_q}，大约要航行多少{au}？",
        "计算所需航行时间：{distance_q} ÷ {speed_q}。",
        "我想知道以{speed_q}航行{distance_q}的耗时。",
        "从这里到锚地{distance_q}，速度{speed_q}，航行多长时间？",
        "若要航行{distance_q}且速度为{speed_q}，需要的时间是多少？",
        "航段{distance_q}，速度{speed_q}，求耗时。",
    ],
    "convert.any": [
        "{value_q}等于多少{to_u}？", "把{value_q}换算成{to_u}。", "{value_q}合多少{to_u}？",
        "请将{value_q}转换为{to_u}。", "Convert {value_q} to {to_u}.", "{value_q} in {to_u}?",
        "单位换算：{value_q}换成{to_u}。", "记录里写的是{value_q}，换成{to_u}是多少？",
        "请把{value_q}改写成以{to_u}为单位的数值。", "{value_q}折算成{to_u}是多少？",
        "我需要以{to_u}为单位的数值，原始数据是{value_q}。", "系统只接受{to_u}，{value_q}该录入多少？",
        "How many {to_u} is {value_q}?", "{value_q}相当于几{to_u}？", "帮我换算一下：{value_q}是多少{to_u}。",
        "换算{value_q}，目标单位{to_u}。", "已知{value_q}，求对应的{to_u}数值。",
        "请问{value_q}用{to_u}来表示是多少？", "把单位从原来的写法改成{to_u}：{value_q}。",
        "{value_q}，换成{to_u}。", "仪器读数{value_q}，请换算到{to_u}。", "将数值{value_q}按{to_u}重新表示。",
    ],
    "convert.distance": [
        "航线长度{value_q}，合多少{to_u}？", "两站相距{value_q}，换算成{to_u}是多少？", "测线长{value_q}，请用{to_u}表示。",
        "离岸距离{value_q}，等于多少{to_u}？", "这次航行走了{value_q}，折合多少{to_u}？", "海图上量得{value_q}，换算为{to_u}。",
        "电缆铺设长度{value_q}，用{to_u}表示是多少？", "The route is {value_q} long. How long is it in {to_u}?",
        "距离{value_q}换成{to_u}是多少？", "考察区宽{value_q}，合计多少{to_u}？",
    ],
    "convert.speed": [
        "航速{value_q}，合多少{to_u}？", "船速{value_q}换算成{to_u}是多少？", "海流流速{value_q}，等于多少{to_u}？",
        "风速表显示{value_q}，请换算为{to_u}。", "这艘船跑{value_q}，换成{to_u}是多少？", "巡航速度{value_q}，用{to_u}表示是多少？",
        "The ship's speed is {value_q}. What is that in {to_u}?", "速度{value_q}换成{to_u}。",
        "拖曳速度{value_q}折合多少{to_u}？", "最高航速{value_q}，相当于多少{to_u}？",
    ],
    "chain.distance": [
        "根据{card}，这艘船的航程是多少{au}？", "{card}记录了航速和航时，请算出航程。", "查一下{card}，然后计算该船走过的距离。",
        "请依据{card}中的数据求航行距离。", "{card}里的船跑了多远？", "Use {card} to find the distance travelled.",
        "以{card}为准，计算总航程（单位{au}）。", "请先检索{card}，再算出它的航程。", "{card}对应航次的航行距离是多少？",
        "我手上只有{card}，帮我求出航程。", "From {card}, how far did the vessel go?", "按{card}上的数据，船一共航行了多少{au}？",
        "{card}这次航行有多长距离？", "需要{card}的航程，请查资料后计算。", "调出{card}，计算该航次里程。",
        "根据资料库中的{card}，算一下航程。", "请结合{card}求出该船航行的路程。", "利用{card}的数据，求航程是多少{au}。",
        "{card}的船走了多少{au}？请查后计算。", "看看{card}，告诉我这一航次的总航程。",
    ],
    "chain.speed": [
        "根据{card}，该船的平均航速是多少{au}？", "{card}记录了航程和用时，请算出平均速度。", "查{card}，求这艘船的航速。",
        "请依据{card}计算平均船速。", "{card}里的船开得有多快？", "Use {card} to compute the average speed.",
        "以{card}为准，平均航速是多少{au}？", "先检索{card}，再算出它的速度。", "{card}对应航次的平均速度是多少？",
        "根据资料库中的{card}算一下航速。", "按{card}上的数据，船的平均速度是多少{au}？", "From {card}, what was the average speed?",
        "调出{card}，计算该航次的平均航速。", "请结合{card}求该船速度。", "看看{card}，告诉我这一航次的平均速度。",
    ],
    "chain.time": [
        "根据{card}，这段航行需要多长时间？", "{card}给出了航程和航速，请算出航行时长。", "查{card}，求这艘船需要航行多久。",
        "请依据{card}计算所需航时。", "{card}里的航段要开几个小时？", "Use {card} to compute the travel time.",
        "以{card}为准，航行时间是多少{au}？", "先检索{card}，再算出所需时间。", "{card}对应航次需要多少{au}？",
        "根据资料库中的{card}算一下耗时。", "按{card}上的数据，航行要花多长时间？", "From {card}, how long is the voyage?",
        "调出{card}，计算该航段的航行时长。", "请结合{card}求所需航行时间。", "看看{card}，告诉我这一航段要开多久。",
    ],
    # Explicit look-ups; only ever paired with cards that are absent from the corpus.
    "lookup_missing": [
        "查一下{card}的内容；找不到的话告诉我还需要什么。", "请调出{card}。如果资料库里没有，说明需要我补充什么。",
        "{card}写了什么？查不到就直接说缺什么资料。", "我要看{card}的记录，没有的话请告诉我。",
        "帮我检索{card}；若无此记录请提示补充信息。", "Look up {card}; if it is missing, tell me what you need.",
        "{card}的资料能找到吗？找不到请说明。", "{card}在不在资料库里？不在的话我该提供什么？",
        "检索{card}的原始记录，没有就请我补充。", "确认一下{card}是否存在，并告诉我其中的记录。",
        "检查{card}的内容，若资料缺失请指出。", "调取{card}看看；资料不全的话提醒我。",
    ],
    # Computation requests that warn about inconsistent records; only paired with conflicting cards.
    "conflict_hint": [
        "请用{card}的数据计算；若记录互相矛盾，先问我。", "{card}可能有多个版本，请检查后再计算。",
        "{card}要用来计算，若数据彼此打架就别硬算。", "查{card}并计算，如果资料前后不一致，请提出来。",
        "Use {card} for the calculation; if records disagree, ask me first.", "先核对{card}的记录是否一致，再进行计算。",
        "请检索{card}后计算，若发现矛盾数据请向我确认。", "根据{card}计算；出现两条不同记录时请说明。",
        "调取{card}进行计算，遇到相互冲突的数据先暂停并询问。", "用{card}算一下，记录不唯一的话告诉我。",
    ],
    "retrieve": [
        "资料库里有没有能回答“{q}”的原文？请摘一句并标注[文档编号]。",
        "{q}——请在资料库中找到对应原文，照抄一句，再写上[文档编号]。",
        "帮我查一下资料：{q} 只需返回原文和[文档编号]。",
        "我需要引用资料原文来回答这个问题：{q} 格式：原文[文档编号]。",
        "请检索与“{q}”相关的资料，给出一句原文，并在句末加[文档编号]。",
        "Find the source sentence for: {q} Quote it exactly and add its [文档编号].",
        "问题：{q}\n请从资料库摘录原文作答，结尾附[文档编号]。",
        "针对{q}这个问题，资料库怎么说？请原文引用并注明[文档编号]。",
        "写报告要用到“{q}”的资料原文，麻烦找一句给我，带上编号。",
        "请给出能支撑以下问题的资料原句及其编号：{q}",
        "查询资料库：{q}。返回格式为原句加[文档编号]，原句保持原样。",
        "{q} 请在资料里找答案，引用原文并标注[文档编号]。",
        "我在整理文献，问题是“{q}”，请摘录一条原文证据，并标编号。",
        "Please search the ocean corpus for: {q} Reply with the exact sentence and its [文档编号].",
        "关于{q}，找一句资料原话给我，后面加上[文档编号]。",
        "请检索“{q}”，把检索到的原文句子连同[文档编号]一起返回。",
        "从资料库中引用一句话来回答：{q}（注明[文档编号]）",
        "想看看资料原文是怎么回答“{q}”的，摘一句并附编号。",
        "{q}\n——引用资料库原文作答，句末附[文档编号]。",
        "需要证据：{q}。请提供一句资料原文和对应的[文档编号]。",
        "请帮我在海洋资料中查找：{q}，只返回原文句子和[文档编号]。",
        "用资料库里的原句回答：{q} 记得写上[文档编号]。",
        "检索并引用：{q}。输出：原文[文档编号]。",
        "我想确认“{q}”在资料中的说法，请直接摘录原句并标注编号。",
        "Search: {q} Then quote one sentence from the result with its [文档编号].",
        "{q} 这个问题请用资料原文回答，不要自己总结，附[文档编号]。",
        "下面的问题需要出处：{q} 原句照抄，并给出[文档编号]。",
        "资料检索：{q}\n要求：摘录原文一句，末尾加[文档编号]。",
        "能不能在资料库里找到“{q}”的相关原文？找到后原样贴出并附编号。",
        "引用资料库内容回答{q}，格式为“原文[文档编号]”。",
        "请搜索资料并摘抄原文：{q}（需要[文档编号]）",
        "回答前先查资料：{q} 请只给出原文和[文档编号]。",
        "我要一句原文作为依据，问题是：{q} 别忘了[文档编号]。",
        "Look up “{q}” in the corpus and quote the matching sentence with its [文档编号].",
        "这个问题有资料可以引用吗：{q} 有的话请原文摘录并标注[文档编号]。",
        "请在海洋资料库中检索{q}，并引用原文一句，注明[文档编号]。",
        "依据资料原文回答“{q}”，原句后面加上[文档编号]。",
        "找一条资料原文来说明：{q} 输出原句和[文档编号]即可。",
        "资料里关于“{q}”的原句是什么？请附[文档编号]。",
        "{q} 请给出资料原文证据（原句+[文档编号]）。",
    ],
    "direct": [
        "以下内容已经确认：{e} 请原样输出这段文字。", "原文如下：{e}\n直接重复原文即可，无需检索。",
        "请把这句话原封不动地发回来：{e}", "已核实记录：“{e}”请复述，不要改动任何字。",
        "Repeat the following record exactly, no lookup needed: {e}", "下面这条资料我已经给你了：{e} 请直接回答这条资料本身。",
        "复制下面的记录作为回答，不要调用工具：{e}", "资料已提供：{e}\n请原样返回。", "请逐字重复这段海洋记录：{e}",
        "{e}\n——请把上面这句原样回复给我。", "不用查资料，把这句话照着写一遍：{e}", "确认无误的记录：{e} 请直接输出。",
        "请回显以下文本（不做任何修改）：{e}", "这是已知资料，原样给我即可：{e}", "我给你一条记录，你原样返回：{e}",
        "Echo this verified note back verbatim: {e}", "请原样输出引号内的文字：“{e}”", "资料内容就是下面这句，请直接重复：{e}",
        "把下面这条海洋记录完整复述一遍：{e}", "无需检索，直接返回这条记录：{e}", "下面是同事发来的记录：{e} 请一字不差地转述。",
        "请原样返回下列内容：{e}", "这句是标准表述，请原文输出：{e}", "记录如下，照抄即可：{e}", "Return this sentence unchanged: {e}",
        "手头资料就这一句：{e} 原样回答即可。", "请把这段已知资料作为答案原样给出：{e}", "{e} 以上为已核实内容，请原样重复。",
        "转述以下记录，不得增删：{e}", "直接复制这一句作为回复：{e}",
    ],
    # (asked operation, missing field): only the other quantity is given, so the answer is a clarification.
    "clarify.distance.speed": [
        "船航行了{hours_q}，航程是多少？", "我们开了{hours_q}，走了多远？", "航行时间{hours_q}，求航行距离。",
        "这艘船跑了{hours_q}，能算出里程吗？", "日志写着航行{hours_q}，航速那一栏空着，航程是多少？",
        "Distance after sailing for {hours_q}?", "科考船出港后航行了{hours_q}，请算航程。",
        "只知道航行了{hours_q}，不知道航速，能算出航程吗？", "航速未知，航行时长为{hours_q}，请给出航程。", "开了{hours_q}的船，航程多少？",
    ],
    "clarify.distance.hours": [
        "船速{speed_q}，航程是多少？", "调查船以{speed_q}航行，走了多远？", "已知航速{speed_q}，求航行距离。",
        "这艘船开{speed_q}，一共跑了多少？", "航速{speed_q}的船航程多少？", "Speed is {speed_q}. How far did it go?",
        "以{speed_q}巡航，请计算航程。", "航速{speed_q}，但航行了多久没记下来，航程是多少？",
        "只有航速{speed_q}这一条数据，请算航程。", "科考船保持{speed_q}，里程是多少？",
    ],
    "clarify.speed.hours": [
        "船航行了{distance_q}，平均航速是多少？", "调查船走了{distance_q}，速度多少？", "航程{distance_q}，求平均速度。",
        "这段{distance_q}的航线，船开得多快？", "已知航行距离{distance_q}，航速是多少？",
        "The ship covered {distance_q}. What was its average speed?", "科考船完成了{distance_q}的测线，平均船速是多少？",
        "航程{distance_q}，用时不清楚，平均速度是多少？", "只记录了距离{distance_q}，请求出航速。", "走航{distance_q}，请算航速。",
    ],
    "clarify.speed.distance": [
        "船开了{hours_q}，平均航速是多少？", "调查船航行{hours_q}，速度是多少？", "用时{hours_q}，求平均速度。",
        "这艘船跑了{hours_q}，开得多快？", "已知航行时间{hours_q}，航速是多少？", "It sailed for {hours_q}. What was its speed?",
        "科考船作业航行{hours_q}，平均船速是多少？", "航行{hours_q}，但没测距离，平均航速是多少？",
        "仅有航行时长{hours_q}，请算速度。", "航行{hours_q}之后，平均速度是多少？",
    ],
    "clarify.time.distance": [
        "船速{speed_q}，需要航行多久？", "以{speed_q}航行，要多长时间？", "航速{speed_q}，求航行时间。",
        "这艘船开{speed_q}，几个小时能到？", "已知速度{speed_q}，航时是多少？", "At {speed_q}, how long will the trip take?",
        "科考船保持{speed_q}前往站位，要开多久？", "船速{speed_q}，目的地多远还不知道，要开多久？",
        "只给了航速{speed_q}，请算航行时间。", "按{speed_q}计算，需要航行几小时？",
    ],
    "clarify.time.speed": [
        "航程{distance_q}，需要多长时间？", "要航行{distance_q}，得多久？", "距离{distance_q}，求航行时间。",
        "去{distance_q}外的站位要开几个小时？", "已知航程{distance_q}，航时是多少？", "How long to cover {distance_q}?",
        "科考船要完成{distance_q}的测线，需要多久？", "航程{distance_q}，船速还没定，需要多长时间？",
        "只有距离{distance_q}这项数据，请算航时。", "走完{distance_q}要多少时间？",
    ],
    # Synthetic voyage-card bodies, always labelled as practice data.
    "card.speed_hours": [
        "合成练习，非实测：航速{speed_q}，航行{hours_q}。", "合成练习，非实测：船速 {speed_q}；航时 {hours_q}。",
        "合成练习，非实测：记录航速{speed_q}，持续{hours_q}。", "合成练习，非实测：vessel speed {speed_q}, sailing time {hours_q}.",
    ],
    "card.distance_hours": [
        "合成练习，非实测：航程{distance_q}，用时{hours_q}。", "合成练习，非实测：航段长 {distance_q}；航时 {hours_q}。",
        "合成练习，非实测：本航段{distance_q}，历时{hours_q}。", "合成练习，非实测：route length {distance_q}, time {hours_q}.",
    ],
    "card.distance_speed": [
        "合成练习，非实测：航程{distance_q}，航速{speed_q}。", "合成练习，非实测：计划航程 {distance_q}；计划船速 {speed_q}。",
        "合成练习，非实测：待航距离{distance_q}，预定航速{speed_q}。", "合成练习，非实测：distance {distance_q}, planned speed {speed_q}.",
    ],
}

# ReAct v3.1 contrast categories (new categories only, so v3 families keep their splits).
# {rid} is a record number that is never a quantity; {given_cn}/{missing_cn}/{asked_cn} name fields.
CONTRAST_CATEGORIES = {
    "id_lead": [
        "航次编号{rid}：", "记录{rid}：", "（船舶编号{rid}）", "工单{rid}：", "测线编号{rid}，", "{rid}号航次：",
        "日志条目{rid}：", "样本批次{rid}，", "ID {rid}: ", "站位{rid}附近，", "调查任务{rid}：", "航段代码{rid}，",
    ],
    "id_tail": [
        "（记录编号{rid}）", "记录号：{rid}。", "对应航次{rid}。", "编号{rid}仅用于归档。", "（任务单{rid}）",
        "备注：船舶编号{rid}。", "Ref {rid}.", "该条目编号为{rid}。", "（日志{rid}）", "所属航次：{rid}。",
    ],
    "clarify_id": [
        "记录编号{rid}的航次只记了{given_cn}{given_q}，没有{missing_cn}，{asked_cn}是多少？",
        "{rid}号记录里只有{given_cn}，{missing_cn}一栏是空的，能算出{asked_cn}吗？",
        "航次{rid}：{given_cn}{given_q}，{missing_cn}未知。请给出{asked_cn}。",
        "请根据航次{rid}的日志求{asked_cn}；日志里有{given_cn}{given_q}，但{missing_cn}没记。",
        "{rid}这条记录缺{missing_cn}，只有{given_cn}{given_q}，{asked_cn}怎么算？",
        "调查船{rid}只上报了{given_cn}，没有上报{missing_cn}，{asked_cn}是多少？",
        "关于记录{rid}：已知{given_cn}{given_q}，{missing_cn}缺失，求{asked_cn}。",
        "编号{rid}的航次{missing_cn}没有测到，{given_cn}是{given_q}，{asked_cn}可以定下来吗？",
        "我手里有{rid}号航次的{given_cn}{given_q}，没有{missing_cn}，请算{asked_cn}。",
        "{rid}：{missing_cn}数据丢失，仅存{given_cn}。{asked_cn}是多少？",
        "工单{rid}要填{asked_cn}，可是只有{given_cn}{given_q}、缺{missing_cn}。",
        "航次{rid}的{missing_cn}还没报上来，先按{given_cn}{given_q}给我{asked_cn}。",
    ],
    "direct.delimited": [
        "下面方括号中的句子是已确认的记录：【{e}】请把方括号里的句子原样给我。",
        "资料：「{e}」\n只需复述引号中的文字。",
        "请照抄书名号里的内容：《{e}》",
        "引用内容如下——“{e}”——请原样返回引号内的话，不要改动。",
        "记录正文（括号中）：（{e}）请输出括号中的正文。",
        "【已核实】『{e}』请只返回『』里面的内容。",
        "这条记录放在方括号里了，直接原样输出即可：【{e}】",
        "Please return only the text inside the brackets: [{e}]",
        "我把资料标在「」里：「{e}」。只要这段，原文照写。",
        "以下是同事转来的记录，正文在中括号内，前面的话不用管。【{e}】请复述正文。",
        "请输出引号中的原文，不要包含其他说明：“{e}”",
        "资料片段《{e}》，把书名号里的文字原样写出来。",
        "说明：括号外的文字都不用输出。正文：（{e}）",
        "记录如下【{e}】，复制方括号里的部分作为回答。",
        "这里有一段已知资料「{e}」，无需检索，原样作答。",
        "请原样转写下列方括号中的内容，不加任何别的字：【{e}】",
    ],
    "chain_form.distance": [
        "航次登记表的“航程”一栏还空着，数据见{card}，请算好填上。", "请把{card}这次航行的里程算出来，写进日志。",
        "汇总表需要{card}的航程（{au}），请核算。", "根据{card}登记本航次走过的距离。",
        "台账里{card}的航程待录入，请计算后给出。", "Fill in the distance for {card} in the log ({au}).",
        "{card}的航程还没统计，请查卡后算出来。", "表格要填{card}的总航程，请给出数值。",
        "请核算{card}的航行距离，用于月度汇总。", "帮我把{card}的航程算出来录入系统。",
    ],
    "chain_form.speed": [
        "航次登记表的“平均航速”一栏还空着，数据见{card}，请算好填上。", "汇总表需要{card}的平均速度（{au}），请核算。",
        "台账里{card}的航速待录入，请计算后给出。", "Fill in the average speed for {card} ({au}).",
        "请把{card}的平均航速算出来，写进日志。", "{card}的平均速度还没统计，请查卡后算出来。",
        "表格要填{card}的航速，请给出数值。", "帮我把{card}的平均航速算出来录入系统。",
        "请核算{card}的平均船速，用于月度汇总。", "根据{card}登记本航次的平均航速。",
    ],
    "chain_form.time": [
        "航次登记表的“航行时长”一栏还空着，数据见{card}，请算好填上。", "汇总表需要{card}的预计航时（{au}），请核算。",
        "台账里{card}的航行时间待录入，请计算后给出。", "Fill in the sailing time for {card} ({au}).",
        "请把{card}所需的航行时间算出来，写进日志。", "{card}的航时还没统计，请查卡后算出来。",
        "表格要填{card}的耗时，请给出数值。", "帮我把{card}需要的航行时长算出来录入系统。",
        "请核算{card}的航行时长，用于月度汇总。", "根据{card}登记本航段的预计耗时。",
    ],
    # Same cards, but the request is the original text: contrasts with computing from a card.
    "card_quote": [
        "把{card}的原始记录原样给我，并附[文档编号]。", "{card}上写的是什么？请照抄原文并标注[文档编号]。",
        "请检索{card}，返回卡片原文和[文档编号]，不要计算。", "我只要{card}的原文记录（附[文档编号]），不需要换算。",
        "Quote the record of {card} exactly, with its [文档编号].", "调出{card}，把记录内容一字不差地贴出来，带上[文档编号]。",
        "{card}的卡片内容请原样摘录，末尾写[文档编号]。", "核对用：请给出{card}的原始文字和[文档编号]。",
        "不用算航程，只把{card}的记录原文发我，附[文档编号]。", "请摘录{card}的全文，并在句末加[文档编号]。",
    ],
}

# Earlier ReAct v1/v2 training phrasings: kept train-only so old abilities are rehearsed.
LEGACY_TRAIN = {
    "prefix": ["任务："],
    "suffix": ["只回答数值和单位。"],
    "card_ref": ["模拟航次卡 {cid}"],
    "calc.distance": ["调查船航速为{speed_q}，持续{hours_q}，航程是多少？", "调查船以{speed_q}航行{hours_q}，用工具计算航程。"],
    "calc.speed": ["海洋调查船{hours_q}行驶{distance_q}，平均航速是多少？", "调查船用{hours_q}航行{distance_q}，用工具计算速度。"],
    "calc.time": ["航速{speed_q}的调查船走完{distance_q}需要多久？", "调查船航程{distance_q}，速度{speed_q}，用工具计算时间。"],
    "convert.any": ["请用工具将{value_q}换算成{to_u}。"],
    "convert.distance": ["海洋调查航程为{value_q}，相当于多少{to_u}？"],
    "chain.distance": ["{card}对应的调查船航程是多少{au}？", "先检索{card}，再用计算工具计算该船航程。"],
    "lookup_missing": ["{card}写了什么？缺少资料时请说明需要补充什么。"],
    "conflict_hint": ["{card}的船舶航程是多少？若记录不一致，请先确认。"],
    "retrieve": ["关于‘{q}’，请提供资料库中的原文证据，末尾标注[文档编号]。",
                 "检索资料：{q}\n请原样摘录返回的目标资料原文，并在末尾标注[文档编号]。"],
    "direct": ["下面是已核实的海洋记录：{e}\n只原样返回这段记录，不需要补充资料。"],
    "clarify.distance.speed": ["调查船持续航行{hours_q}，请给出航程。"],
    "card.speed_hours": ["合成练习，非实测：speed={speed_q}，hours={hours_q}。", "模拟练习，非实测：speed={speed_q}，hours={hours_q}。"],
    "card.distance_hours": ["合成练习，非实测：distance={distance_q}，hours={hours_q}。"],
    "card.distance_speed": ["合成练习，非实测：distance={distance_q}，speed={speed_q}。"],
}

# Plan text of the erroneous earlier call in recovery histories (context only, never supervised).
HISTORY_PLANS = ["计算航程。", "先算一下。", "调用计算器。", "按题意计算。", "尝试计算。"]

# ReAct v2 held-out val/test phrasings, rewritten with the placeholders above. They are never
# sampled; the generator and tests use them only to keep training phrasings away from them.
V2_HELDOUT_PREFIXES = ["海洋调查记录处理：", "请完成以下海上作业资料核对，并遵循输出要求："]
V2_HELDOUT = [
    "航程表记载{value_q}，请以{to_u}表示这段航程。",
    "已知航速{speed_q}与航行时长{hours_q}，求调查船走过的距离。",
    "调查航程{distance_q}，船以{speed_q}匀速行驶，求所需小时数。",
    "某海上任务总长{distance_q}，总时长{hours_q}，求{au}表示的航速。",
    "要填写{au}制报表，原始海里值是{value_q}，填写什么数值？",
    "某调查船保持{speed_q}匀速经过{hours_q}，请给出累计航程。",
    "以{speed_q}完成{distance_q}的海上任务，耗时应填多少{au}？",
    "从记录得知船舶走过{distance_q}并用时{hours_q}，其平均速度为多少？",
    "请根据{card}的航速和时长确定总里程，统一以{au}表示。",
    "需要补全{au}制航程报表，已知依据仅有{card}，请给出应填写的航程。",
    "请为问题‘{q}’找出资料中的一句原文，并附上[文档编号]。",
    "待核对的问题是：{q}。答复须由资料原文和[文档编号]组成，不要改写。",
    "请照录这份已确认海洋记录的内容：{e} 不要添加别的文字。",
    "这是全部需要使用的资料：【{e}】。请只输出括号内的原文，不作外部查询。",
    "船舶记录只有时长，未记载速度。记录编号{card}，目前能确定航程吗？",
    "请为编号{card}的调查航次补填航程。日志只提供航行时长，尚无船速数据。",
    "请找出航次{card}的资料；无法定位时请告诉我需补充的信息。",
    "需要核验{card}这条航次记录的内容；查无记录时请向我索取依据。",
    "请核对{card}的记录。如果不同记录不能支持唯一航速，应先向我确认。",
    "以{card}为依据填写航程；不允许自行选择互相矛盾的数据，请说明待确认事项。",
]
